trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: Checkout@1

 
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true


  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

 
  - script: |
      python sales_data_pipeline.py
    displayName: 'Run sales data pipeline'


  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'raw_sales_data.csv'
      ArtifactName: 'RawData'
      publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'processed_sales_data.csv'
      ArtifactName: 'ProcessedData'
      publishLocation: 'Container'
