# -*- coding: utf-8 -*-
"""Email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2cZPjg8Wg2sdNVZe-lXY4gMPuEFopww
"""

from google.colab import files
uploaded = files.upload()

import smtplib
import os
from email.message import EmailMessage

sender_email = os.getenv("EMAIL_FROM")
receiver_email = os.getenv("EMAIL_TO")
email_password = os.getenv("EMAIL_PASSWORD")

msg = EmailMessage()
msg["Subject"] = "top5_lowest_performing_stores"
msg["From"] = sender_email
msg["To"] = receiver_email
msg.set_content("Hello,\n\nI hope this mail finds you\nPlease find the attached CSV file generated by the pipeline.\n\nRegards,\nKarthika Azure Devops")

csv_file_path = "top5_lowest_performing_stores.csv"
with open(csv_file_path, "rb") as f:
    msg.add_attachment(f.read(), maintype="text", subtype="csv", filename="lowest_performing_store.csv")

try:
    with smtplib.SMTP("smtp.gmail.com", 587) as smtp:
        smtp.starttls()
        smtp.login(sender_email, email_password)
        smtp.send_message(msg)
        print("least prerforming stores report successfully sent with attachments.")
except Exception as e:
    print(f"Failed to send email: {e}")